name: Linting and codestyle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: knowsuchagency/poetry-install@v2
      with:
        # Have poetry create a virtualenv for the project on installation.
        create-virtualenv: false # optional, default is false
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        # pip install pylint
        poetry install
    - name: Code style
      run: |
        poetry shell
        black $(git ls-files '*.py')
    - name: Analysing the code with pylint
      run: |
        poetry shell
        pylint $(git ls-files '*.py')
